project:
  title: "gh-page-smk"
  type: "website"
  output-dir: docs

website:
  title: "gh-page-smk"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: Simplex
    css: styles.css
    toc: true

