project:
  title: "gh-page-smk"
  type: "website"
  output-dir: docs

website:
  title: "gh-page-smk"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: analysis/index.qmd
        text: Analysis
      - about.qmd
      # - menu:
      #   - href: analysis/analysis1.qmd
      #     text: analysis

format:
  html:
    theme: sandstone
    css: styles.css